preinst: If monit not found then fail.

diff --git a/usingJSON/debian-armv7l/DEBIAN/preinst b/usingJSON/debian-armv7l/DEBIAN/preinst
--- a/usingJSON/debian-armv7l/DEBIAN/preinst
+++ b/usingJSON/debian-armv7l/DEBIAN/preinst
@@ -13,6 +13,9 @@ if [ -x /usr/bin/monit ]; then
     if [ ! -d "/etc/monit/conf.d" ]; then
         mkdir /etc/monit/conf.d
     fi
+else
+    echo "Fail, monit not found."
+    exit 1
 fi
 
 
diff --git a/usingJSON/debian-x86_64/DEBIAN/preinst b/usingJSON/debian-x86_64/DEBIAN/preinst
--- a/usingJSON/debian-x86_64/DEBIAN/preinst
+++ b/usingJSON/debian-x86_64/DEBIAN/preinst
@@ -9,6 +9,13 @@ if [ -x /usr/bin/monit ]; then
     monit -g CONTROL stop
     monit
     sleep 1
+
+    if [ ! -d "/etc/monit/conf.d" ]; then
+        mkdir /etc/monit/conf.d
+    fi
+else
+    echo "Fail, monit not found."
+    exit 1
 fi
 
 
